FROM golang:alpine as builder

WORKDIR $GOPATH/src/github.com/mraxus/mystery-golang-alpine

# Install musl so that we can build a static binary
RUN apk -f update && apk -q -f add musl musl-dev musl-tools git gcc
COPY . ./
RUN go get

# Build it statically https://dominik.honnef.co/posts/2015/06/go-musl/
RUN CC=$(which musl-gcc) go build --ldflags '-linkmode external -extldflags "-static"' -o /o2


FROM alpine:latest
WORKDIR /
COPY --from=builder /o2 /o2
ENTRYPOINT ["/o2"]
